[metadata]
name="Relatório Conversas"
customer="PF"

[[field]]
key="ano"
name="Ano"
query="""
SELECT DISTINCT
    extract(YEAR FROM created_at)
FROM
    "0239d9b4-cc8c-4b33-866e-ac9b9a2a7a86".chatbot_conversation_messages
"""
deps=[]


[[field]]
key="mes"
name="Mês"
query="""
SELECT DISTINCT
    extract(MONTH FROM created_at)
FROM
    "0239d9b4-cc8c-4b33-866e-ac9b9a2a7a86".chatbot_conversation_messages
WHERE
    extract(YEAR FROM created_at) = $1
"""
deps=["ano"]


[[field]]
key="dia"
name="Dia"
query="""
SELECT DISTINCT
    extract(MONTH FROM created_at)
FROM
    "0239d9b4-cc8c-4b33-866e-ac9b9a2a7a86".chatbot_conversation_messages
WHERE
    extract(YEAR FROM created_at) = $1
"""
deps=["mes","ano" ]


[[button]]
key="csv"
name="Baixar Relatorio"
query="""
SELECT DISTINCT
    extract(YEAR FROM created_at) AS year
FROM
    "0239d9b4-cc8c-4b33-866e-ac9b9a2a7a86".chatbot_conversation_messages
WHERE
    extract(YEAR FROM created_at) = $1
    AND extract(MONTH FROM created_at) = $2
"""
deps=["ano", "mes", "dia", "canal_acesso"]
